name: Update IP List (With Region & Delay)

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次（cron格式：分 时 日 月 周）
  workflow_dispatch:  # 手动触发

jobs:
  update-ip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # 升级到最新版，提升稳定性
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'  # 缓存依赖，加速运行
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # 安装所有依赖（包含urllib3，避免SSL警告）
          pip install requests urllib3
          
      - name: Delete Old Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 2
          keep_minimum_runs: 6
          
      - name: Run IP Collection Script
        run: python ${{ github.workspace }}/collect_ips.py
        
      - name: Commit & Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          # 同时跟踪两个文件，避免未跟踪报错
          git add ${{ github.workspace }}/ip.txt ${{ github.workspace }}/senflare.txt
          # 仅当文件有变化时提交（避免空提交）
          if git diff --cached --quiet; then
            echo "No changes to commit (IP list unchanged)"
          else
            git commit -m "Update IP List: $(date +'%Y-%m-%d %H:%M') | Available: $(wc -l < senflare.txt)"
            git push origin main --force-with-lease  # 安全推送，避免冲突
          fi
