name: Basic IP Check Workflow

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  check-ips:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests urllib3
          
      - name: Run IP check script
        run: python collect_ips.py
        
      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add ip.txt senflare.txt
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update available IPs: $(date +'%Y-%m-%d %H:%M')"
            git push origin main
          fi
